version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: campusconnect-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: Campus_Connect
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Api-Backend/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - campusconnect-net
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: campusconnect-redis
    ports:
      - "6379:6379"
    networks:
      - campusconnect-net
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: api-backend:6
    container_name: campusconnect-backend
    env_file:
      - ./Api-Backend/.env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3100:3100"
    networks:
      - campusconnect-net

  frontend:
    image: client-frontend:3
    container_name: campusconnect-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - campusconnect-net

volumes:
  mysql_data:


networks:
  campusconnect-net:
    driver: bridge
